### ISSUE TITLE
RuntimeError: probability tensor contains either `inf`, `nan` or element < 0

### ISSUE THREAD

**Issue by sunhao** [DLLXW/baby-llama2-chinese#33]
Traceback (most recent call last):
  File "/home/afan/worksapce/train/baby-llama2-chinese/infer.py", line 91, in <module>
    generated_tokens = model.generate(input_tokens, num_samples, max_new_tokens, temperature=temperature, top_k=top_k)
  File "/home/afan/anaconda3/envs/baby/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/afan/worksapce/train/baby-llama2-chinese/model.py", line 341, in generate
    idx_next = torch.multinomial(probs, num_samples=1)
RuntimeError: probability tensor contains either `inf`, `nan` or element < 0

model.py代码中这个位置
logits = self(idx_cond)
print(logits) 结果是这样
tensor([[[nan, nan, nan,  ..., nan, nan, nan]]], device='cuda:1',dtype=torch.float16)

可以帮忙看下是什么原因导致的么？

**Comment by jh01231230** [comment]
看上去输入数据有问题，你调用generate()方法的输入x你能自查一下是不是不太对？
